- name: Privilege Escalation
  hosts: all

  tasks:
    - name: Install HTTPD
      yum:
        name: httpd
        state: latest
     : Platform linux on host 172.31.85.175 is using the discovered Python interpreter at /usr/bin/python,
but future installation of another Python interpreter could ch
