- name: template example
  hosts: all
  vars:
  - name: copy 
    MY_URL: "XYZ"
  tasks:
      copy: 
        src: ./demo.txt
         dest: ~/copy.txt

         - name: template
        template:
        src: ./demo.txt
        dest: ~/template.txt
