- name: template example
  hosts: all
  - name: copy 
  vars:
    MY_URL: "XYZ"
  tasks:
      copy: 
        src: ./demo.txt
        dest: ~/copy.txt

    - name: template
      template:
        src: ./demo.txt
        dest: ~/template.txt
