- name: variable playbook example
  hosts: all
  vars:
    URL: "global.google.com"
    var_files: "var.yml"
  tasks: 
     - name: print message
       debug:
          msg: "Welcome TO {{ URL }}"
     - name: 2nd print message
       debug:
       msg: "Welcome to "     