- name: variable playbook example
  hosts: all
  vars:
    URL:
    VAR1: "HITESH MANKAR"
  tasks: 
     - name: print message
       debug:
          msg: "Hello wworld {{ URL }}, my name is {{var}}
          