- name: variable playbook example
  hosts: all
  vars:
    URL: "global.google.com"
 # vars_files: 
  #   - "./var.yml"
#  vars_prompt:
 #    - name: URL
 #      prompt: "please enter the url:"
  #     private: false
  tasks:
     - name: print message
       debug:
         msg: "welcome to {{ URL }}"  
     - name: print node's OS
       debug:
         msg: "OS is {{ ansible_distribution }}"
     - name: print machine name
       debug:
         msg: "Hostname = {{ ansible_nodename }}"  
     - name: register variable
       shell: echo "Hello World"
       register: OUT
     - name: print register
