- name: playbook to create webserver
  hosts: all
  tasks:
     -name: install httpd
     yum:
       state: latest
       name: httpd
 
    
       service:
         state: started
         name: httpd
         enabled: true  

     - name: Deploy website
