- name: playbook to create webserver
  hosts: all
  tasks:
    - name: install httpd
      yum:
       state: latest
       name: httpd
 
    - name: start httpd daemon
      service:
         state: started
         name: httpd
         enabled: true  

    - name: Deploy website
      copy:
        src: ./index.html
        dest: /var/www/html
