- name: playbook to create webserver
  hosts: all
  tasks:
  yum:
    state: latest
     name: httpd

     - name: start httpd daemon 
      service:
         state: started
         name: httpd
         enabled: true  