    - name: install httpd
      yum:
       state: latest
       name: httpd
 
    - name: start httpd daemon
      service:
         state: started
         name: httpd
         enabled: true  

    - name: Deploy website
      copy:
        src: ./index.html
        dest: /var/www/html/index.html

    - name: Deploy website contain
      copy:
        src: ./index_files
        dest: /var/www/html/
