- name: Install Java
  yum:
     state: latest
     name: java

- name: Download tomcat 8
  get_url: https://dlcdn.apache.org/tomcat/tomcat-8/v8.5.81/bin/apache-tomcat-8.5.81.tar.gz
    dest: /opt/


- name: Extract tomcat to /opt
  unarchive:
    src: /opt/{{ TOMCAT_ZIP }}
    dest: /opt/   
    remote_src: true

- name: Deploy webapp    
  copy:
    src: ./student.war
    dest: /opt{{TOMCAT_DIR}}/webapp/studenta.war

- name: start service
  shell: /opt/{{TOMCAT_DIR}}/bin/catalina.sh  start