- name: Install Java
  yum:
     state: latest
     name: java
- 
- name: download & unarchive tomcat10 
  unarchive:
         src: https://dlcdn.apache.org/tomcat/tomcat-8/v8.5.81/bin/apache-tomcat-8.5.81.tar.gz
         dest: /opt/
         remote_src: yes
   

- name: Extract tomcat to /opt
  unarchive:
    src: /opt/{{ apache-tomcat-8.5.81.tar.gz }}
    dest: /opt/
    remote_src: true

- name: Deploy webapp    
  copy:
    src: ./student.war
    dest: /opt{{TOMCAT_DIR}}/webapp/studenta.war

- name: start service
  shell: /opt/{{TOMCAT_DIR}}/bin/catalina.sh  start