- name: install java
  yum:
     state: latest
     name: openjdk-java

- name: Download tomcat 8
- get_url:
    url: "{{ TOMCAT_URL }}"
    dest: /opt/

- name: Extract tomcat to /opt
  unarchive:
    src: /opt/{{ TOMCAT_ZIP }}
    dest: /opt/   
    
- name: start service
  shell: /opt/{{T}}    