- name: Install Java
  yum:
     state: latest
     name: java
 - name: Create a Tomcat Directory
      file:
        path: /opt/tomcat10
        owner: tomcat
        group: tomcat
        mode: 755
        recurse: yes
 
    - name: download & unarchive tomcat10 
      unarchive:
        src: https://mirrors.estointernet.in/apache/tomcat/tomcat-10/v10.0.4/bin/apache-tomcat- 10.0.4.tar.gz
        dest: /opt/tomcat10
        remote_src: yes
   
- name: Extract tomcat to /opt
  unarchive:
    src: /opt/{{ TOMCAT_ZIP }}
    dest: /opt/   
    remote_src: true

- name: Deploy webapp    
  copy:
    src: ./student.war
    dest: /opt{{TOMCAT_DIR}}/webapp/studenta.war

- name: start service
  shell: /opt/{{TOMCAT_DIR}}/bin/catalina.sh  start