- name: install java
  yum:
     state: latest
     name: openjdk-java

- name: download tomcat 8
  get_url:
    url: "{{ TOMCAT_URL }}"
    dest: /opt/


- name: Extract tomcat to /opt
  unarchive:
    src: /opt/{{ TOMCAT_ZIP }}
    dest: /opt/   
    remote_src: true

- name: Deploy webapp    
  copy:
    src: ./student.war
    dest: /opt{{TOMCAT_DIR}}/webapp/studenta.war

- name: start service
  shell: /opt/{{TOMCAT_DIR}}/bin/catalina.sh  start