- name: Install Java
  yum:
     state: latest
     name: java


- name: Download tomcat 8
- get_url:
    url: "{{ TOMCAT_URL }}"
    dest: /opt/
 
- name: Extract tomcat to /opt
  unarchive:
         src: /opt/https://dlcdn.apache.org/tomcat/tomcat-8/v8.5.81/bin/apache-tomcat-8.5.81.tar.gz
         dest: /opt/
         remote_src: yes

- name: Deploy webapp
  copy:
    src: ./student.war
    dest: /opt/{{TOMCAT_DIR}}/webapps/student.war


- name: start service
  shell: /opt/{{TOMCAT_DIR}}/bin/catalina.sh  start